#
# project Euler problem 30 - Digit fifth powers
# Created by Payam Behjat
# How many distinct terms are in the sequence generated by ab for 
# Find the sum of all the numbers that can be written as the sum of 
# fifth powers of their digits.
#

1.upto(500000) do |num|
	if (num == num.to_s.split('').map(&:to_i).map{|x| x ** 5}.reduce(:+)) then
		p num
	end
end

